// YouTube metadata for the tutorial episodes, used by components/TutorialsJsonLd.tsx.
// Sourced 2026-10-09 from each public watch page (https://www.youtube.com/watch?v=<id>):
// name = videoDetails.title, description = first paragraph of
// videoDetails.shortDescription, uploadDate = microformat uploadDate (also the
// itemprop="uploadDate" meta), duration = videoDetails.lengthSeconds. Nothing
// here is estimated; re-source from YouTube if a video is re-uploaded or edited.
// Episodes 20 and 21 have no video yet and are deliberately absent.
export type TutorialVideo = { id: string; name: string; description: string; uploadDate: string; duration: string };

export const TUTORIAL_VIDEOS: TutorialVideo[] = [
  { id: "YzZuZiprSao", name: "CueDeck Tutorial #1 — The Production Console for Live Events (Overview)", description: "CueDeck is a realtime production console for managing live conferences and events — session states, roles, digital signage, AI agents, and more. In this first episode I'll give you a full overview of what CueDeck does and walk you through every feature we'll cover in this series.", uploadDate: "2026-03-16T06:16:28-07:00", duration: "PT3M7S" },
  { id: "v0CM_4XKMcQ", name: "CueDeck Tutorial #2 — Create Your First Event & Add Sessions", description: "In this episode I'll walk you through creating a live conference event in CueDeck from scratch — event details, sessions, rooms, speakers, flags, and the running order. By the end you'll have a full programme ready to run live.", uploadDate: "2026-03-16T06:16:29-07:00", duration: "PT3M47S" },
  { id: "NDeJfYDrcns", name: "CueDeck Tutorial #3 — Running a Live Event: The Full Session State Machine", description: "This is the core of CueDeck. In this episode I'll walk through the full session lifecycle — from PLANNED to READY, CALLING, LIVE, HOLD, OVERRUN, and ENDED — live on screen. You'll also see the delay nudge cascade and the speaker arrived flag.", uploadDate: "2026-03-16T06:16:30-07:00", duration: "PT4M40S" },
  { id: "DxrMZCBU4Cs", name: "CueDeck Tutorial #4 — Roles & Team Invites: Right Access for Every Person", description: "CueDeck has 6 roles — Director, Stage, AV, Interpretation, Registration, and Signage. In this episode I'll show you exactly what each role can see and do, and walk through the team invite flow so you can get your whole crew connected before show day.", uploadDate: "2026-03-16T06:16:32-07:00", duration: "PT3M5S" },
  { id: "2ZqYHw2TI_E", name: "CueDeck Tutorial #5 — Broadcast Bar: Send Messages to Your Entire Crew Instantly", description: "No more group chats during a live event. The CueDeck broadcast bar sends a message to every connected device instantly — stage managers, AV engineers, interpretation booths, everyone. In this episode I'll show you how it works and how to set up presets for your most common messages.", uploadDate: "2026-03-16T06:16:33-07:00", duration: "PT2M35S" },
  { id: "vq4hef-0uCg", name: "CueDeck Tutorial #6 — Delay Cascade: Handle Overruns Without Losing Your Programme", description: "When a session runs long, CueDeck's delay cascade automatically shifts every subsequent session in your programme — no manual edits, no spreadsheet recalculations. In this episode I'll show you exactly how it works, what anchor sessions do, and how to reset delays instantly.", uploadDate: "2026-03-16T06:16:35-07:00", duration: "PT7M54S" },
  { id: "ZD8xXyBt7ec", name: "CueDeck Tutorial #7 — Digital Signage: Set Up Your First Display in 5 Minutes", description: "CueDeck's signage system turns any browser tab into a live display for your venue. Lobby monitors, stage-side screens, backstage tablets — all updating in realtime from your console. In this episode I'll show you how to create your first display, generate a URL, and set up a rotating sequence.", uploadDate: "2026-03-16T06:16:36-07:00", duration: "PT9M8S" },
  { id: "ntM9NZkPWR8", name: "CueDeck Tutorial #8 — All 11 Signage Display Modes Explained", description: "CueDeck has 11 display modes for your venue screens — from a full session schedule to a speaker countdown to a time×room programme grid. In this episode I walk through every single one so you know exactly which mode to use where.", uploadDate: "2026-03-16T06:16:38-07:00", duration: "PT9M59S" },
  { id: "5pnrAtIQBZI", name: "CueDeck Tutorial #9 — Stage Confidence Monitor: Never Lose Track of What's Live", description: "The Stage Confidence Monitor is a fullscreen overlay that shows the current LIVE session in giant text — always visible, always in sync. In this episode I'll show you how to open it, what each state looks like, and how directors use it to keep eyes on stage instead of on a screen.", uploadDate: "2026-03-16T06:16:39-07:00", duration: "PT7M0S" },
  { id: "33BRPEqgbc4", name: "CueDeck Tutorial #10 — Stage Timer: A Speaker-Facing Countdown That Runs Itself", description: "The Stage Timer is a fullscreen countdown display for the speaker — mounted on a monitor facing the stage so presenters can self-manage their time. In this episode I'll set one up from scratch and walk through all six visual states: standby, live (green/amber/red), overrun, and hold.", uploadDate: "2026-03-16T06:16:40-07:00", duration: "PT8M36S" },
  { id: "TIT9jqmMRNo", name: "CueDeck Tutorial #11 — AI Incident Advisor: Your Crisis Co-Pilot for Live Events", description: "When something goes wrong on stage — tech failure, no-show speaker, fire alarm — the AI Incident Advisor gives you a prioritised action plan in seconds. In this episode I'll show you how it works and demo it with a real incident scenario.", uploadDate: "2026-03-16T06:16:41-07:00", duration: "PT6M18S" },
  { id: "TE98wtdXehk", name: "CueDeck Tutorial #12 — AI Cue Engine: Automatic Pre-Session Checklists", description: "The CueDeck Cue Engine fires 8 minutes before every session starts with an AI-generated readiness checklist — mic tested? slides loaded? speaker arrived? In this episode I'll show you how it works and why it catches more problems than any manual reminder system.", uploadDate: "2026-03-16T06:16:42-07:00", duration: "PT5M47S" },
  { id: "oZwY2JgGap0", name: "CueDeck Tutorial #13 — AI Post-Event Report: From Raw Data to Polished Debrief", description: "After the last session ends, CueDeck's AI Report Generator analyses your event data and produces a full debrief — session variance, incident log, executive summary, and AI narrative — ready to send to your client or team. In this episode I'll walk through every tab.", uploadDate: "2026-03-16T06:16:43-07:00", duration: "PT7M6S" },
  { id: "lk71z8RF9v0", name: "CueDeck Tutorial #14 — Timeline & Programme Displays: Attendee-Facing Screens", description: "CueDeck's Timeline and Programme signage modes turn your lobby monitors and corridor screens into live conference boards that update automatically as sessions start and end. In this episode I'll set up both modes and show the difference between them.", uploadDate: "2026-03-16T06:16:44-07:00", duration: "PT7M9S" },
  { id: "c4AnQanOUJ8", name: "CueDeck Tutorial #15 — Sponsor Logos: Rotating Branding on Your Venue Screens", description: "CueDeck's Sponsor signage mode displays rotating sponsor logos on your venue screens — automatically cycling through sponsors at configurable durations. In this episode I'll upload logos, set per-sponsor timing, and build a sequence that mixes sponsors with session info.", uploadDate: "2026-03-16T06:16:45-07:00", duration: "PT6M35S" },
  { id: "kRl2s2Y1lOo", name: "CueDeck Tutorial #16 — Event Log & Post-Event Report: Full Accountability After Every Event", description: "CueDeck logs every state transition, every team action, every delay — with timestamps and actor names. In this episode I'll show you the event log, the AI variance report, and how to export a CSV from Supabase for client billing and debrief.", uploadDate: "2026-03-16T06:16:46-07:00", duration: "PT7M43S" },
  { id: "GOpXBCaK7VI", name: "CueDeck Tutorial #17 — Keyboard Shortcuts & Command Palette: Power User Mode", description: "In a live event, your eyes are on stage — not on a mouse. CueDeck's keyboard shortcuts and Cmd+K command palette let you run the entire console without ever clicking. In this episode I'll walk through every shortcut and demo a full session transition without touching the mouse.", uploadDate: "2026-03-16T06:16:48-07:00", duration: "PT6M45S" },
  { id: "K4pFwyoJYc0", name: "CueDeck Tutorial #18 — Mobile & Tablet: Run Your Event from Any Device", description: "CueDeck runs in any browser — no app to install. Stage managers on an iPad, registration on a phone, director on a tablet. In this episode I'll show you exactly how CueDeck adapts to smaller screens and give you a practical setup guide for each role.", uploadDate: "2026-03-16T06:16:49-07:00", duration: "PT6M46S" },
  { id: "T6Xbtl8BMhM", name: "CueDeck Tutorial #19 — Plans & Billing: Free, Pro, Per-Event & Enterprise", description: "CueDeck has a plan for every event size — from a free single-event trial to unlimited Pro to per-event credits for occasional users. In this episode I'll walk through each plan, show the user profile panel, and explain how to upgrade via Stripe.", uploadDate: "2026-03-16T06:16:50-07:00", duration: "PT6M40S" },
];
